### ISSUE TITLE
Exception : Invalid status 6512 (Unknown reason)

### ISSUE THREAD

**Issue by unknownfeature** [LedgerHQ/blue-loader-python#128]
Hello

Trying to run this command:
```
 python3 -m ledgerblue.loadApp \
        --targetId 0x31100004  \
        --fileName bin/"app".hex \
        --appFlags 0x00 \
        --appName "RSK Sign" \
        --appVersion 4 \
        --icon `cat icon.hex` \
        --path ""
```
Getting
```
Generated random root public key : b'044bee7960dc1a4597d4510a4179214650f1f8f1c8fd3de859cc98939524bc239dc5f16d3f81a8862652ad5a5e32333cf2b00be650066957a04356f96d76fec42b'
Using test master key b'044bee7960dc1a4597d4510a4179214650f1f8f1c8fd3de859cc98939524bc239dc5f16d3f81a8862652ad5a5e32333cf2b00be650066957a04356f96d76fec42b' 
Using ephemeral key b'0434a0ad668c6553f5c1dc0915c347e1494ca6f6b29fdc7eae04f8bfff79027b47d63e655781db6d3edb165d0058b33bf7e6f4193ad644b4673525e1ff8b4ae663'
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "/Users/bitch/.pyenv/versions/3.7.16/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/bitch/.pyenv/versions/3.7.16/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bitch/PycharmProjects/rsk-powhsm/ledger/test/venv/lib/python3.7/site-packages/ledgerblue/loadApp.py", line 268, in <module>
    loader.createAppNoInstallParams(args.appFlags, appLength, args.appName, args.icon, path, None, None, string_to_bytes(args.appVersion))
  File "/Users/bitch/PycharmProjects/rsk-powhsm/ledger/test/venv/lib/python3.7/site-packages/ledgerblue/hexLoader.py", line 364, in createAppNoInstallParams
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/Users/bitch/PycharmProjects/rsk-powhsm/ledger/test/venv/lib/python3.7/site-packages/ledgerblue/hexLoader.py", line 207, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/Users/bitch/PycharmProjects/rsk-powhsm/ledger/test/venv/lib/python3.7/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6512 (Unknown reason)
```

ledgerblue version ledgerblue==0.1.48 
Device
```
Product is genuine
SE Version 2.1.0
MCU Version 1.1
MCU Hash 04302e3131
```

Does anyone know what that could potentially be? It goes through the secret negotiation and then drops in `createAppNoInstallParams`. Is is some sort of incompatibility or am I passing bad args?

Running on Mac OS

Thank you in advance!

**Comment by unknownfeature** [comment]
The issue is with my sdk
