### ISSUE TITLE
Is my ledger legit ?

### ISSUE THREAD

**Issue by c0mm0n** [LedgerHQ/blue-loader-python#15]
Hi,

I've tried to use the python command to check if my Ledger is legit (ordered from Ledger directly).

I get this:

```python -m ledgerblue.checkGenuine --targetId 0x14200000
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/ledgerblue/checkGenuine.py", line 131, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId, args.issuerKey)
  File "/Library/Python/2.7/site-packages/ledgerblue/checkGenuine.py", line 40, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Library/Python/2.7/site-packages/ledgerblue/comm.py", line 130, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6484
```

Is it a concern ?

**Comment by c0mm0n** [comment]
Ok solved, was not using the correct product ID
```python -m ledgerblue.checkGenuine --targetId 0x31100002
Product is genuine

**Comment by sayeghr** [comment]
This issue should be marked closed.
