### ISSUE TITLE
CommException: Exception : Invalid status 6d00

### ISSUE THREAD

**Issue by epan** [LedgerHQ/blue-loader-python#26]
What does `Invalid status 6d00` mean? Is there something wrong with my nano? 

# Info
- Python 3.6.4
- Ledger nano s

# Output
```
| => python3 -m ledgerblue.checkGenuine --targetId 0x31100002

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ledgerblue/checkGenuine.py", line 129, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId, args.issuerKey)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ledgerblue/checkGenuine.py", line 40, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ledgerblue/comm.py", line 130, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6d00

**Comment by splut** [comment]
Also reporting this issue when using the "runApp" script.
In your case, try python 2.7.

**Comment by mkjmkjmkj** [comment]
Same issue here, with:
Python 3.5.2
Ledger Nano s with firmware 1.3.1 and 1.4.1 (update didn't change the output of checkGenuine)
I can't use python 2.7 because: ECPy requires Python '>=3' but the running Python is 2.7.12

Any suggestions on what is causing this and how to resolve it?

**Comment by AronVanAmmers** [comment]
@mkjmkjmkj there's a workaround for running with Python 2.7 here https://github.com/LedgerHQ/blue-loader-python/issues/29. However running with Python 2.7 gives me the same results as with Python 3 (the same stack trace you posted).

Also, when the Fido U2F app is active on the Ledger, it gives me `Invalid channel` rather than `Invalid sequence`.

**Comment by Da5hes** [comment]
same error status here when trying to load MCU, both with python3 and 2.7 with all dependencies in place

**Comment by pmprete** [comment]
I got this error when selecting the BTC app in the device but i was calling it using the nodejs new ledger.eth(comm);
