### ISSUE TITLE
ECPy requires Python '>=3' but the running Python is 2.7.12

### ISSUE THREAD

**Issue by mandelmonkey** [LedgerHQ/blue-loader-python#29]
Readme specifies to use python 2.7 however it wont install ledgerblue
I used python 3.5 to install but having issues when installing the icon on the blue-app-btc

which python should be used?

**Comment by couillardcharles** [comment]
you can try to run `pip install ECPy==0.8.1` before

**Comment by NicolasDorier** [comment]
Same issue, followed by,

```
PS C:\Users\NicolasDorier\Documents\Sources\Ledger\ledgerapps\blue-app-btc> pip install ECPy==0.8.1
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pip\__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "c:\python27\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "c:\python27\lib\site-packages\pip\download.py", line 37, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "c:\python27\lib\site-packages\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
```

**Comment by mandelmonkey** [comment]
latest python loader works for me using pip install ECPy==0.8.1

**Comment by sharma02gaurav** [comment]
You can use `aliyun-python-sdk-core-v3` to solve the issue
