### ISSUE TITLE
RunApp.py fails with 'Exception : Invalid status 6d00'

### ISSUE THREAD

**Issue by splut** [LedgerHQ/blue-loader-python#31]
- Python 2.7
- ECPy version==0.8.1 (to get around '**ECPy requires Python '>=3' but the running Python is 2.7.13**' issue)

Command:
`$ python -m ledgerblue.runApp --targetId 0x31100002 --appName Bitcoin`

Trace:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/ledgerblue/runApp.py", line 61, in <module>
    loader.runApp(args.appName)
  File "/usr/local/lib/python2.7/site-packages/ledgerblue/hexLoader.py", line 242, in runApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/usr/local/lib/python2.7/site-packages/ledgerblue/hexLoader.py", line 86, in exchange
    return self.card.exchange(apdu)
  File "/usr/local/lib/python2.7/site-packages/ledgerblue/comm.py", line 130, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6d00
```

**Comment by hkjn** [comment]
@btchip: Do you think we can close this issue as well, with #67 merged?

(I intended to close both this issue and #26 automatically by merging #67, but apparently 'Fixes #26 #31' isn't understood by Github..)
