### ISSUE TITLE
loadApp fails on MacOS with: Invalid status 6700 (Unknown reason)

### ISSUE THREAD

**Issue by riordant** [LedgerHQ/blue-loader-python#34]
OS: MacOS Sierra 10.12.6
device: Ledger Nano S
firmware: 1.4.1
Script(s): `loadApp` 
Python: 3.6.4 (virtualenv)
command (from blue-app-btc root): 
`python -m ledgerblue.loadApp --appFlags 0x50 --curve secp256k1 --targetId 0x31100003 --fileName bin/app.hex --appName "Bitcoin" --path ""`
Version: 0.1.17 (commit ab589175f3551133fd6e6645a9cb5d845cb9892f - ie. non pip version)
trace:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/tadhgriordan/.virtualenvs/ledger/lib/python3.6/site-packages/ledgerblue-0.1.17-py3.6.egg/ledgerblue/loadApp.py", line 248, in <module>
    loader.createAppNoInstallParams(args.appFlags, appLength, args.appName, args.icon, path, None, None, args.appVersion)
  File "/Users/tadhgriordan/.virtualenvs/ledger/lib/python3.6/site-packages/ledgerblue-0.1.17-py3.6.egg/ledgerblue/hexLoader.py", line 344, in createAppNoInstallParams
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/Users/tadhgriordan/.virtualenvs/ledger/lib/python3.6/site-packages/ledgerblue-0.1.17-py3.6.egg/ledgerblue/hexLoader.py", line 194, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/Users/tadhgriordan/.virtualenvs/ledger/lib/python3.6/site-packages/ledgerblue-0.1.17-py3.6.egg/ledgerblue/comm.py", line 129, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6700 (Unknown reason)
```
status `6700` is `incorrect length`.

**Comment by Penple03** [comment]
Getting this too on both Windows 10 and Ubuntu. Going to attempt it on another Ledger in a few days.

Device: Ledger Nano S
Python: 2.7.14 (on both)
Firmware: 1.4.2
Version: 0.1.17 (pip version)

Windows 10:
```
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ledger\lib\site-packages\ledgerblue\loadApp.py", line 251, in <module>
    loader.createAppNoInstallParams(args.appFlags, appLength, args.appName, args.icon, path, None, None, args.appVersion)
  File "C:\ledger\lib\site-packages\ledgerblue\hexLoader.py", line 346, in createAppNoInstallParams
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "C:\ledger\lib\site-packages\ledgerblue\hexLoader.py", line 194, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "C:\ledger\lib\site-packages\ledgerblue\comm.py", line 133, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6700 (Unknown reason)
```
Ubuntu:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/ledger/lib/python2.7/site-packages/ledgerblue/loadApp.py", line 251, in <module>
    loader.createAppNoInstallParams(args.appFlags, appLength, args.appName, args.icon, path, None, None, args.appVersion)
  File "/home/user/ledger/local/lib/python2.7/site-packages/ledgerblue/hexLoader.py", line 346, in createAppNoInstallParams
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)                        
  File "/home/user/ledger/local/lib/python2.7/site-packages/ledgerblue/hexLoader.py", line 194, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/home/user/ledger/local/lib/python2.7/site-packages/ledgerblue/comm.py", line 133, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6700 (Unknown reason)
```

**Comment by btchip** [comment]
Are you using the latest https://github.com/ledgerhq/nanos-secure-sdk and application version ?

**Comment by Penple03** [comment]
For compilation? Yes. However I'm not aware of a requirement for nanos-secure-sdk to load.

**Comment by PhilippeBonnaz** [comment]
Status 6700 may be due to missing --dataSize argument for loadApp.
Which app are you trying to build, this argument should be retrieved automatically from the COMMON_LOAD_PARAMS in Makfile.defines in nanos-secure-sdk
https://github.com/LedgerHQ/nanos-secure-sdk/blob/0be513c4bd85ad03f446da25a35425f480ccdc3f/Makefile.defines#L27

**Comment by Penple03** [comment]
I ended up having to load using the `--tlv` flag, didn't catch it in the docs. Working fine though now, thanks!

**Comment by btchip** [comment]
ok, closing
