### ISSUE TITLE
Check Genuine - Indentation error

### ISSUE THREAD

**Issue by felipetdsa** [LedgerHQ/blue-loader-python#52]
When doing 
 $python -m ledgerblue.checkGenuine --targetId 0x31100003

Got the error:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/anaconda3/lib/python3.6/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/anaconda3/lib/python3.6/site-packages/ledgerblue/checkGenuine.py", line 110
    return ret
             ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by DarthJahus** [comment]
There's a space before `return ret` at line 110. It should be replaced by a tab.

I'd also recommend to handle the case when given `targetId` doesn't finish with 2 or 3. Just in case.
