### ISSUE TITLE
Do nano x support loadApp

### ISSUE THREAD

**Issue by bitcodernull** [LedgerHQ/blue-loader-python#61]
I want to load app to nano x , i get the following errors:

 python -m ledgerblue.loadApp --appFlags 0x00 --delete --tlv --targetId 0x33000004 --fileName bin/app.hex --appName "Test" --appVersion 0.0.1 --icon 0100000000ffffff00ffffffffffffffffffff73ce3186218463ccc7f887f08ff1cff9ffffffffffff

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/shangzuo/work/document/ledger/ledger/lib/python2.7/site-packages/ledgerblue/loadApp.py", line 176, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/Users/shangzuo/work/document/ledger/ledger/lib/python2.7/site-packages/ledgerblue/deployed.py", line 115, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Users/shangzuo/work/document/ledger/ledger/lib/python2.7/site-packages/ledgerblue/comm.py", line 141, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 69d5 (Unknown reason)

the error is the same as the pro issue:
https://github.com/LedgerHQ/blue-loader-python/issues/58

**Comment by justinvforvendetta** [comment]
i have the same issue, i cant use ledgerblue to load scripts, or even check genuine on the ledger nano x.

also left a note in https://github.com/LedgerHQ/blue-loader-python/issues/58 as well

**Comment by TamtamHero** [comment]
Nano X with current firmware can only be loaded with Ledger signed apps.

**Comment by justinvforvendetta** [comment]
@TamtamHero so how can we test our integration? that is what we were asked to do.

**Comment by justinvforvendetta** [comment]
@TamtamHero so we cant do any testing? when/will that change?
