### ISSUE TITLE
documentation broken, can't get started

### ISSUE THREAD

**Issue by chrisbward** [LedgerHQ/blue-loader-python#77]
followed the instructions on ubuntu 20.04...

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/developer/Tools/ledger/blue-loader-python/ledgerblue/loadApp.py", line 296, in <module>
    loader.createAppNoInstallParams(args.appFlags, appLength, args.appName, args.icon, path, None, None, string_to_bytes(args.appVersion))
  File "/home/developer/Tools/ledger/blue-loader-python/ledgerblue/hexLoader.py", line 45, in string_to_bytes
    return bytes(x, 'ascii')
TypeError: encoding without a string argument

``` 

```
pip show ledgerblue
Name: ledgerblue
Version: 0.1.32
Summary: Python library to communicate with Ledger Blue/Nano S
Home-page: https://github.com/LedgerHQ/blue-loader-python
Author: Ledger
Author-email: hello@ledger.fr
License: UNKNOWN
Location: /home/developer/Tools/ledger/blue-loader-python/ledger/lib/python3.8/site-packages
Requires: hidapi, ecpy, python-u2flib-host, protobuf, pycryptodomex, pillow, future, websocket-client
Required-by: 
``` 
here's my setup;
```
python --version
Python 3.8.2

python -m ledgerblue.loadApp --targetId 0x31100004 --apdu --fileName app.hex --appName Hello --appFlags 0x00 --icon ""
```

**Comment by TamtamHero** [comment]
`make load` is your friend !
You're missing `--appVersion` arg, but really you should not use this command manually, use the app's Makefile instead.
