### ISSUE TITLE
How to make WSL work?

### ISSUE THREAD

**Issue by DoctorLai** [LedgerHQ/blue-loader-python#83]
Hi, 
I am using WSL (Windows SubSystem for Linux), and it always complains "no dongle found", please could you advice how to fix this?

```
python3 -m ledgerblue.loadApp --targetId 0x31100003 --fileName bin\app.hex --icon 0100000000ffffff0000000000fc000c0f3814c822103f101120092005400340018001800000000000 --curve secp256k1 --path "44'/195'" --apdu --appName "Tron" --appVersion "VERSION_NUMBER" --appFlags 0x40 --delete --dataSize 145311 --tlv 
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/ledgerblue/loadApp.py", line 199, in <module>
    dongle = getDongle(args.apdu)
  File "/usr/local/lib/python3.8/dist-packages/ledgerblue/comm.py", line 240, in getDongle
    raise CommException("No dongle found")
ledgerblue.commException.CommException: Exception : No dongle found
```

**Comment by NickP005** [comment]
I have the same problem with virtual box and I'm just using docker.
Have you found a solution to this?

thanks
