### ISSUE TITLE
checkGenuine returns Invalid status 6814 (Unknown reason)

### ISSUE THREAD

**Issue by msteinb** [LedgerHQ/blue-loader-python#96]
Hello, I'm trying to check a Nano S on firmware 2.0.0 by running

```
python3 -m ledgerblue.checkGenuine --targetId 0x31100003
```

The docs indicate that `0x31100003` is correct for my firmware: https://support.ledger.com/hc/en-us/articles/4404382029329-Check-hardware-integrity?support=true.

I'm getting the following error 
```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/moshe/Library/Python/3.8/lib/python/site-packages/ledgerblue/checkGenuine.py", line 137, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId, args.issuerKey)
  File "/Users/moshe/Library/Python/3.8/lib/python/site-packages/ledgerblue/checkGenuine.py", line 44, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Users/moshe/Library/Python/3.8/lib/python/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6814 (Unknown reason)
```
When I try `checkGenuineRemote` it works.
```
python3 -m ledgerblue.checkGenuineRemote --targetId 0x31100003
```
However, the docs indicate the `checkGenuineRemote` is the right script for a Nano X, not a Nano S. What's even more confusing is when I run the command listed for the Nano X (which has a different targetId) on my Nano S, it also tells me the device is genuine:

```
python3 -m ledgerblue.checkGenuineRemote --targetId 0x33000004
```
What's the right command to use for a Nano S running firmware 2.0.0?

**Comment by gokmev** [comment]
I have the same issue, with ledgerblue.checkGenuineRemote, it returns regardless of the targetId I enter, even with some random numbers. If I do "python3 -m ledgerblue.checkGenuine --targetId 0x33000004", ledger asks me if I would allow unsafe manager and shows the public key, so I don't. Not sure what is going on?

**Comment by afds3j8** [comment]
I also have this issue with a ledger nano s. I python3 -m ledgerblue.checkGenuineRemote --targetId 0xxxxxxxx returns device genuine. checkGenuine returns ledgerblue.commException.CommException: Exception : Invalid status 6814 (Unknown reason)

**Comment by ThomasDev62** [comment]
Have you able to resolve your issues?

**Comment by gokmev** [comment]
I contacted Ledger support and did the the same as ClaudeF4491 above after receiving this message from the Ledger support: 
"My apologies for the late reply. The targetId that should be used to check hardware integrity depends on the OS of your computer (we need to update our guide regarding that).

Could you please increment the targetId by one by running the following command: python -m ledgerblue.checkGenuine --targetId 0x31100004

I hope this will solve your issue and I remain available should you need more help."

After allowing unsafe manager like mentioned in the link below, it does say it is genuine:
https://www.reddit.com/r/ledgerwallet/comments/m8ae3w/allow_unsafe_manager_when_running/
