### ISSUE TITLE
Nano S Plus - Invalid status 6d06 on ledgerblue.checkGenuine

### ISSUE THREAD

**Issue by rchenzheng** [LedgerHQ/blue-loader-python#98]
Was meaning to run a hardware integrity test on my Nano S Plus, instead I get an exception

Running Python `3.10.2` using virtualenv in MacOS and libtool 2.4.7 installed via brew

## Command ran 
```
python3 -m ledgerblue.checkGenuine --targetId 0x33100004
```

## Error

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/ledgerblue/checkGenuine.py", line 137, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId, args.issuerKey)
  File "/usr/local/lib/python3.10/site-packages/ledgerblue/checkGenuine.py", line 44, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/usr/local/lib/python3.10/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6d06 (Unknown reason)
```

**Comment by ggcaponetto** [comment]
same for me

any fix?

**Comment by rchenzheng** [comment]
> same for me
> 
> any fix?

I gave up on it but `Ledger Live` itself runs it on boot

**Comment by ggcaponetto** [comment]
thanks @rchenzheng . after connecting it to the ledger live and setting it up (+ firmware update) the python script works.
